### ISSUE TITLE
New date patterns

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/processors#584] opened 2021-12-26 18:54 UTC
Hi @EgoLaparra,
Can you please add two more date/range patterns for:
"month of X", e.g., "month of January", and
"before mid-July"?

Thank you!
Mihai

**Comment by MihaiSurdeanu** [comment] 2021-12-27 02:41
I added the "month of X" pattern in this PR:
https://github.com/clulab/processors/pull/585

So, the only thing left to do is "before mid-July".

**Comment by EgoLaparra** [comment] 2021-12-28 16:08
@MihaiSurdeanu how do you want to normalize such expressions? Something like "before mid-July" -> "XXXX-XX-XX -- XXXX-07-15"? Do you want us to also cover "the beginning of July" and "the end of July"?

**Comment by MihaiSurdeanu** [comment] 2021-12-28 16:30
@EgoLaparra: yes on all questions :)

I think "mid"|"middle", "beginning"|"start", "end" probably captures most situations. Not sure yet how to handle the "mid-July" as a single token. Maybe we should split it into "mid" and "July"?

**Comment by EgoLaparra** [comment] 2021-12-28 17:08
I think we should split it so we can handle all those cases in a similar way.

**Comment by MihaiSurdeanu** [comment] 2022-01-02 21:28
@EgoLaparra: This tokenization issue has now been fixed in this PR:
https://github.com/clulab/processors/pull/586
which has been merged in master.

"mid-July" is tokenized into "mid" and "July" (the dash disappears).
Thanks!

**Comment by MihaiSurdeanu** [comment] 2022-01-02 21:29
@kwalcock : I wonder what other prefixes similar to "mid-" should be tokenized out?

**Comment by kwalcock** [comment] 2022-01-02 22:38
The article at https://www.proofreadnow.com/blog/master-prefixes-and-suffixes-with-hyphens suggests trans- and non- along with mid-.  Perhaps they would help with parsing.

Hyphens are used after all prefixes preceding a proper noun, a number, or an abbreviation (e.g., "trans-Atlantic network," "mid-1960s," or "non-GABAergic responses").

There's also this list:

Use a hyphen after the following prefixes in most words: "all-", "cross-", "ex-", and "self-" (e.g., “self-service,” “ex-boyfriend,” “all-encompassing”). Most "servo-" words are also hyphenated with the following two exceptions: “servomechanism” and “servomotor.”

For our numeric parsing do we account for -fold in any way?

**Comment by kwalcock** [comment] 2022-01-02 22:46
"bi" and "semi" are often not written with hyphens but the construction is fairly productive.  If these prefixes are added to dates, are they still recognized?

**Comment by MihaiSurdeanu** [comment] 2022-01-03 01:45
From these, I think the following should be tokenized because: (a) they commonly appear as separate tokens as well, and (b) they may impact the downstream components in processors: bi, semi, non, all.

**Comment by MihaiSurdeanu** [comment] 2022-01-03 02:01
These are addressed in this PR:
https://github.com/clulab/processors/pull/587

I'll merge it as soon as tests pass.

**Comment by EgoLaparra** [comment] 2022-01-03 16:45
> @EgoLaparra: This tokenization issue has now been fixed in this PR: #586 which has been merged in master.
> 
> "mid-July" is tokenized into "mid" and "July" (the dash disappears). Thanks!

Great, thanks!

**Comment by EgoLaparra** [comment] 2022-01-03 16:46
Sorry, I accidentally closed the issue 😅

**Comment by EgoLaparra** [comment] 2022-01-21 20:54
@Mihai, for what cases is this rule required? Do not `date-yyyy-mm-dd`, `date-dd-mm-yyyy`, ... cover dates with numeric months? I've tried commenting it out and all tests pass.
https://github.com/clulab/processors/blob/44fbb004aa4abef7d5fcfffce29a48cfa21c5960/main/src/main/resources/org/clulab/numeric/atomic.yml#L11-L17
The issue is that I need to produce dates with only month names to solve cases like `mid-July`, and that rule is not very convenient since it interprets single numbers (from 1 to 12) as months. Could we safely remove it?

**Comment by MihaiSurdeanu** [comment] 2022-01-21 21:02
Maybe... Can you please try to remove it and see if all unit tests pass?

**Comment by EgoLaparra** [comment] 2022-01-21 23:20
All the tests pass, it seems that we can remove it. I'll make the change and add a rule to identify single-month dates.

**Comment by MihaiSurdeanu** [comment] 2022-01-22 02:07
Sounds good. Thank you @EgoLaparra !

**Comment by MihaiSurdeanu** [comment] 2022-02-08 19:47
Has this been merged in master @EgoLaparra ? Close the issue?

**Comment by EgoLaparra** [comment] 2022-02-08 20:45
Not totally yet. The support for modifiers (`mid-July`) will be merged with https://github.com/clulab/processors/pull/596

**Comment by MihaiSurdeanu** [comment] 2022-02-09 19:09
close this now?

**Comment by EgoLaparra** [comment] 2022-02-09 19:51
Yes!

**Closed by EgoLaparra** 2022-02-09 19:51 UTC
